Updating dump_analyser.sh to handle some edge case where the binary info is not correctly handled
In some of the edge case the binary have truncated path like below:

```
error: file specified in --file (-f) option doesn't exist: '/home/yugabyte/yb-software/yugabyte-2.19.0.0-b190-centos-x
86_64/postgres/bin/po'
```

Which results in failure as there is no `/bin/po` util. This should be `/bin/postgres` . 

So the script has been modified (Credit: Eugene) to filter the correct name with command.

```
diff /home/support/bin/dump_analyser.sh.20230718 /home/support/bin/dump_analyser.sh
51,55c51
< #strings "$file_name" | grep -E "/yugabyte/yb-software/yugabyte-" | head -n 1 > /tmp/yb_db_version & PID=$!
<
< strings "$file_name" | grep -P "^/.*/yugabyte/yb-software/.*/bin/" | sort | uniq -c | sort -nr | head -1 | awk {'print $2'} > /tmp/yb_db_version & PID=$!
<
<
---
> strings "$file_name" | grep -E "/yugabyte/yb-software/yugabyte-" | head -n 1 > /tmp/yb_db_version & PID=$!
66,68d61
<
<
```